#! /usr/bin/env python3

import types
import os, sys
import pathlib
import math

MACHINES_FILE = pathlib.Path(os.path.dirname(os.path.realpath(__file__))) / "machines"

def parse_machines():
    machines = {}
    with open(MACHINES_FILE) as f:
        for _line in f.readlines():
            line = _line.strip()
            if line.startswith("# "):
                group = line.strip("# ")

            if not line or line.startswith("#"): continue

            instance, cpu, memory, price, *accel = line.split(", ")

            entry = types.SimpleNamespace()
            entry.cpu = int(cpu.split()[0])
            entry.memory = int(memory.split()[0])
            entry.price = float(price[1:])
            entry.group = group
            entry.name = instance

            machines[entry.name] = entry
    return machines


RESERVED_CPU = 2
RESERVED_MEM = 4

EXTRA_USERS = 1 # count as if there was +10% of users

def main():
    machine_type, _user_count, _cpu, _memory = sys.argv[1:]

    machines = parse_machines()

    user_count = int(_user_count)

    notebook_size = {"cpu": float(_cpu), "memory":float(_memory)}
    machine_size = machines[machine_type]

    print(f"Reserved cpu={RESERVED_CPU}, mem={RESERVED_MEM}")
    print(f"Machine type:  {machine_type} --> {machine_size}")
    print(f"Notebook size: cpu={_cpu}, mem={_memory}Gi")
    print()

    total_cpu_count = notebook_size["cpu"] * user_count
    total_memory_count = notebook_size["memory"] * user_count

    machine_count_cpu = total_cpu_count / (machine_size.cpu - RESERVED_CPU)
    machine_count_memory = total_memory_count / (machine_size.memory - RESERVED_MEM)

    print(f"Memory requirement: {machine_count_memory:.1f} x {machine_type}")
    print(f"CPU requirement:    {machine_count_cpu:.1f} x {machine_type}")
    print()
    machine_exact_count = max([machine_count_cpu, machine_count_memory])
    machine_count = math.ceil(machine_exact_count)

    print(f"Provisioning {machine_count} {machine_type} machines for running {user_count} users with the notebook size cpu={_cpu}, mem={_memory}")
    notebooks_per_machine = math.ceil(user_count/machine_count)
    unallocated_cpu = machine_size.cpu - notebook_size['cpu'] * notebooks_per_machine
    unallocated_mem = machine_size.memory - notebook_size['memory'] * notebooks_per_machine

    print(f"Expecting {notebooks_per_machine:d} notebooks per node ({unallocated_cpu} cpu and {unallocated_mem}Gi of memory not allocated per node)")
    return machine_count

if __name__ == "__main__":
    try:
        sys.exit(main()) # returns the number of nodes required
    except Exception as e:
        print(f"ERROR: '{' '.join(sys.argv)}' failed: {e.__class__.__name__}: {e}")
        sys.exit(0) # 0 means that an error occured
