#! /usr/bin/env python3

import types
import os, sys
import pathlib
import math

MACHINES_FILE = pathlib.Path(os.path.dirname(os.path.realpath(__file__))) / "machines"

def parse_machines():
    machines = {}
    with open(MACHINES_FILE) as f:
        for _line in f.readlines():
            line = _line.strip()
            if line.startswith("# "):
                group = line.strip("# ")

            if not line or line.startswith("#"): continue

            instance, cpu, memory, price, *accel = line.split(", ")

            entry = types.SimpleNamespace()
            entry.cpu = int(cpu.split()[0])
            entry.memory = int(memory.split()[0])
            entry.price = float(price[1:])
            entry.group = group
            entry.name = instance

            machines[entry.name] = entry
    return machines


RESERVED_CPU = 2
RESERVED_MEM = 4

EXTRA_USERS = 1 # count as if there was +10% of users

MAX_POD_PER_NODE = 250 - 15 # 250 pods allocatable, 15 pods

def main():
    try:
        machine_type, _user_count, _cpu, _memory = sys.argv[1:]
    except ValueError:
        print(f"ERROR: expected 4 arguments: `MACHINE_TYPE, USER_COUNT, CPU, MEMORY`, got {len(sys.argv[1:])}: {sys.argv[1:]}")
        print(f"""Example:
MACHINE="Dell FC640"
USERS=1000

CPU=0.2
MEM=0.750
# or
CPU=1
MEM=4

{sys.argv[0]} "$MACHINE" "$USERS" "$CPU" "$MEM"
""")
        sys.exit(1)

    machines = parse_machines()

    user_count = int(_user_count)

    pod_size = {"cpu": float(_cpu), "memory":float(_memory)}
    machine_size = machines[machine_type]

    print(f"Reserved cpu={RESERVED_CPU}, mem={RESERVED_MEM}")
    print(f"Machine type:  {machine_type} --> {machine_size}")
    print(f"Pod size: cpu={_cpu}, mem={_memory}Gi")
    print()

    total_cpu_count = pod_size["cpu"] * user_count
    total_memory_count = pod_size["memory"] * user_count

    machine_count_cpu = total_cpu_count / (machine_size.cpu - RESERVED_CPU)
    machine_count_memory = total_memory_count / (machine_size.memory - RESERVED_MEM)

    print(f"Memory requirement: {machine_count_memory:.1f} x {machine_type}")
    print(f"CPU requirement:    {machine_count_cpu:.1f} x {machine_type}")
    print()
    machine_exact_count = max([machine_count_cpu, machine_count_memory])
    machine_count = math.ceil(machine_exact_count)

    pods_per_machine = math.ceil(user_count/machine_count)

    # ensure that the expected pod/machine
    if pods_per_machine > MAX_POD_PER_NODE:
        print(f"Computation gives {pods_per_machine} Pods per node on {machine_count}. Increasing the node count to stay below {MAX_POD_PER_NODE} pods/node.")
        pods_per_machine = MAX_POD_PER_NODE
        machine_count = math.ceil(user_count/pods_per_machine)

    print(f"Provisioning {machine_count} {machine_type} machines for running {user_count} users with the pod size cpu={_cpu}, mem={_memory}")
    unallocated_cpu = machine_size.cpu - pod_size['cpu'] * pods_per_machine
    unallocated_mem = machine_size.memory - pod_size['memory'] * pods_per_machine

    print(f"Expecting {pods_per_machine:d} pods per node ({unallocated_cpu:.3f} cpu and {unallocated_mem:.2f}Gi of memory not allocated per node)")

    AWS_MAX_VOLUMES_PER_NODE = 39
    if "xlarge" in machine_type and pods_per_machine > AWS_MAX_VOLUMES_PER_NODE:
        print(f"WARNING: if the Pods have AWS volumes, this configuration won't work (only {AWS_MAX_VOLUMES_PER_NODE} volumes per node is supported)")
        print("See https://docs.openshift.com/container-platform/4.12/storage/persistent_storage/persistent-storage-aws.html")

    return machine_count

if __name__ == "__main__":
    try:
        sys.exit(main()) # returns the number of nodes required
    except Exception as e:
        print(f"ERROR: '{' '.join(sys.argv)}' failed: {e.__class__.__name__}: {e}")
        sys.exit(0) # 0 means that an error occured
