FROM quay.io/centos/centos:stream8

RUN dnf -y --quiet install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
 && dnf install -y --quiet s3cmd gettext \
 && dnf clean all

RUN curl --silent -L https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -o /usr/bin/yq \
 && chmod +x /usr/bin/yq