# based on https://github.com/openshift-psap/llm-load-test/blob/d503eba7f530a610d068b98f7f6bb12d62a98b69/build/Containerfile

# not used by the buildconfig should not be prefix with the image registry location
FROM ci-artifacts:main

# install llm-load-test requirements
RUN python3 -m ensurepip

RUN pip3 install -r projects/llm_load_test/llm-load-test/requirements.txt
