#! /bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
set -x

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $THIS_DIR/topsail_host_config
source $THIS_DIR/has_toolbox

CONTAINER_NAME=${1:-}
CONTAINER_IMAGE=${2:-}

if [[ -z "$CONTAINER_NAME" ]]; then
    echo "ERROR: $0 must receive a container name"
    exit 1
fi

if [[ -z "$CONTAINER_IMAGE" ]]; then
    echo "ERROR: $0 must receive a container image"
    exit 1
fi

if podman inspect --type container $CONTAINER_NAME &>/dev/null; then
    podman stop $CONTAINER_NAME || podman stop $CONTAINER_NAME
    podman rm $CONTAINER_NAME
fi

if has_toolbox; then
    toolbox create $CONTAINER_NAME \
            --image $CONTAINER_IMAGE
else
    podman run \
           --name $CONTAINER_NAME \
           -v "$TOPSAIL_HOME:/topsail" \
           --detach \
           --tty \
           --entrypoint /bin/bash \
           $CONTAINER_IMAGE
fi
