#! /bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
# set -x

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
set -a
source $THIS_DIR/topsail_host_config
source $THIS_DIR/has_toolbox
set +a

if [[ "$#" == 0 ]]; then
    command="cd $TOPSAIL_HOME && $TOPSAIL_TOOLBOX_COMMAND"
else
    command="$@"
fi

env=$(cat $THIS_DIR/topsail_container_env | envsubst)

if has_toolbox; then
    exec toolbox run -c $TOPSAIL_TOOLBOX_NAME -- bash -c "set -a; $env ; set +a; $command"
else
    env_args=()
    while IFS= read -r line; do
        line=$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue  # skip comments and empty lines
        processed_line=$(echo "$line" | envsubst)
        env_args+=("--env" "$processed_line")
    done <<< "$env"

    exec podman exec "${env_args[@]}" -it "$TOPSAIL_TOOLBOX_NAME" /bin/bash
fi
