#! /bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
# set -x

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $THIS_DIR/topsail_host_config

exec $THIS_DIR/topsail_enter "cd $PWD && $TOPSAIL_TOOLBOX_COMMAND"
