#! /bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
# set -x

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$THIS_DIR"/topsail_host_config.default
if [[ -f "$THIS_DIR/topsail_host_config.custom" ]];
then
    source "$THIS_DIR/topsail_host_config.custom"
fi

exec "$THIS_DIR"/topsail_enter "cd $PWD && $TOPSAIL_TOOLBOX_COMMAND"
