#! /bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
# set -x

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
set -a
source $THIS_DIR/topsail_host_config
set +a

if [[ "$#" == 0 ]]; then
    command="cd $TOPSAIL_HOME && $TOPSAIL_TOOLBOX_COMMAND"
else
    command="$@"
fi

env=$(cat $THIS_DIR/topsail_container_env | envsubst)
exec toolbox run -c $TOPSAIL_TOOLBOX_NAME -- bash -c "set -a; $env ; set +a; $command"
