export OPERATOR_NAME="${OPERATOR_NAME:-gpu-operator}"
export OPERATOR_NAMESPACE="${OPERATOR_NAMESPACE:-gpu-operator}"

echo "Using OPERATOR_NAME=${OPERATOR_NAME} and OPERATOR_NAMESPACE=${OPERATOR_NAMESPACE}"
