# based on https://github.com/openshift-psap/llm-load-test/blob/580dce5926380de05c108976a72c8e969346c5c8/build/Containerfile

# not used by the buildconfig should not be prefix with the image registry location
FROM ci-artifacts:main

ARG GRPCURL_VERSION=1.8.7
RUN curl -L https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz | tar xz && \
    chmod 777 grpcurl && mv grpcurl /usr/local/bin/


RUN git clone https://github.com/dagrayvid/ghz.git /src/ghz && \
    cd /src/ghz/cmd/ghz && \
    go build . && \
    mv ghz /usr/local/bin/

RUN git clone https://github.com/openshift-psap/llm-load-test.git /src/llm-load-test
RUN pip3 install -r /src/llm-load-test/requirements.txt
