FROM quay.io/centos/centos:stream8

RUN dnf -y --quiet install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
 && dnf install -y --quiet \
    s3cmd gettext \
    python39 python3-virtualenv \
 && dnf clean all

RUN curl --silent -L https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -o /usr/bin/yq \
 && chmod +x /usr/bin/yq \
 && curl --silent -L https://github.com/benc-uk/locust-reporter/releases/download/v1.2.3/locust-reporter -o /usr/bin/locust-reporter \
 && chmod +x /usr/bin/locust-reporter

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN virtualenv -p /usr/bin/python3.9 $VIRTUAL_ENV \
 && pip3 install --upgrade pip \
 && pip install --quiet --no-cache-dir  \
           locust==2.8.* \
           locust-plugins==2.6.* \
           BeautifulSoup4==4.11.* \
           jinja2==3.0.*
