FROM quay.io/centos/centos:stream9

RUN dnf -y --quiet install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
 && dnf install -y --quiet s3cmd gettext \
 && dnf clean all


# indicate that MD5 isn't used for security purposes, otherwise FIPS cluster block it
# see https://github.com/s3tools/s3cmd/issues/876#issuecomment-468888560
RUN sed -i 's/md5()/md5(usedforsecurity=False)/g' /usr/lib/python*/site-packages/S3/{S3,Utils}.py

RUN curl --silent -L https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -o /usr/bin/yq \
 && chmod +x /usr/bin/yq

