# based on https://github.com/openshift-psap/llm-load-test/blob/d503eba7f530a610d068b98f7f6bb12d62a98b69/build/Containerfile

# not used by the buildconfig should not be prefix with the image registry location
FROM topsail:main

# install `grpcurl`
ARG GRPCURL_VERSION=1.8.7
RUN curl -L https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz | tar xz && \
    chmod 777 grpcurl && mv grpcurl /usr/local/bin/

# install llm-load-test requirements
RUN python3 -m ensurepip

RUN pip3 install -r projects/llm_load_test/subprojects/llm-load-test/requirements.txt
